name: ${project.name}
main: net.roguedraco.infobutton.InfoButtonPlugin
version: ${project.version}
author: TruDan
load: POSTWORLD
depends: [Vault]
softdepend: [Multiverse-Core]
dev-url: ${project.url}
commands:
    ib:
      usage: /ib
      description: General InfoButton Commands
    infobutton:
      usage: /infobutton
      description: General InfoButton Commands