name: {$project.name}
main: net.roguedraco.infobutton.InfoButtonPlugin
version: {$project.version}
author: TruDan
depends: [Vault]
dev-url: {$project.url}
commands:
    ib:
      usage: /ip
      description: General InfoButton Commands
    infobutton:
      usage: /infobutton
      description: General InfoButton Commands